apiVersion: v1
kind: Service
metadata:
  name: multimodal-robot-learning
spec:
  selector:
    app: multimodal-robot-learning
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: LoadBalancer